#Define the list of machines
slurm_cluster = {
    :master => {
        :hostname => "master",
        :ipaddress => "10.10.10.3"
    },
    :worker001 => {                                                              
        :hostname => "worker-001",
        :ipaddress => "10.10.10.4"
    }
}

ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip


#Provisioning inline script
$script = <<SCRIPT
echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
apt-get update
apt-get install -y -q emacs
apt-get install -y -q slurm-llnl
echo "10.10.10.3    master" >> /etc/hosts
echo "10.10.10.4    worker-001 " >> /etc/hosts
cp /home/vagrant/shared/slurm.conf /etc/slurm-llnl/
sudo cp /home/vagrant/shared/munge.service /etc/systemd/system/munge.service
SCRIPT

Vagrant.configure("2") do |global_config|
    slurm_cluster.each_pair do |name, options|
        global_config.vm.define name do |config|

          puts "# --------------------"
          print "HOST: ", name, " ",slurm_cluster[name][:hostname], "\n"
          puts "# --------------------"
          
            #VM configurations
            config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"
          
            config.vm.box = "ubuntu-15.04"
            config.vm.hostname = slurm_cluster[name][:hostname]
            puts config.vm.hostname 
            config.vm.network :private_network, ip: options[:ipaddress]

            config.vm.synced_folder ".", "/home/vagrant/shared"

            #VM specifications

            config.vm.provider :virtualbox do |v|
              # v.gui = true
              v.customize ["modifyvm", :id, "--memory", "512"]
            end

            #VM provisioning
            config.vm.provision :shell,
                :inline => $script
        end
    end
end

