require 'yaml'


ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip


#Provisioning inline script
$script = <<SCRIPT
echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
SCRIPT

def parse_specification(path)
  contents = File.read(path)
  YAML.load(contents)
end

def write_inventory(spec, path)

  File.open(path, 'w') do |fd|
    spec.each do |group,nodes|
      fd << "[#{group}]" << "\n"
      nodes.each do |node|
        fd << "#{node['hostname']}"
        fd << " "
        fd << "ansible_ssh_host=#{node['ipaddress']} ansible_ssh_user=vagrant"
        fd << "\n"
      end
      fd << "\n"
    end
  end

end

spec = parse_specification("spec.yaml")
puts spec

write_inventory(spec, "inventory.txt")



puts system ("cat inventory.txt")

Vagrant.configure("2") do |config|

  # VM configurations
  config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"

  config.ssh.forward_agent = true
  config.vm.box = "ubuntu-15.04"
  config.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/vivid/current/vivid-server-cloudimg-amd64-vagrant-disk1.box"

  # SHARE THE FILESYSTEM
  
  config.vm.synced_folder ".", "/home/vagrant/shared"
  
  # VM specifications
  
  config.vm.provider :virtualbox do |v|
    # v.gui = true
    v.customize ["modifyvm", :id, "--memory", "512"]
  end


  spec.each do |group,nodes|
    nodes.each do |node|

      puts "# --------------------"
      print "HOST: ", node['name'], " ",node['hostname'], "\n"
      puts "# --------------------"

      config.vm.define node['name'] do |vmconfig|
        vmconfig.vm.hostname = node['hostname']
        vmconfig.vm.network :private_network, ip: node['ipaddress']
      end
  
    end

  end

  # ADDEING THE PUBLIC KEY
  config.vm.provision :shell, :inline => $script

  # RUNNING THE ANSIBLE PLAYBOOK
  config.vm.provision "ansible" do |ansible|
     ansible.inventory_path = "inventory.txt"
     ansible.playbook = "playbook.yml"
     ansible.host_key_checking = false
  end


end


